// <auto-generated />
using System;
using DAL.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.DomainClass.Bangluong", b =>
                {
                    b.Property<int>("Maluong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MALUONG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maluong"));

                    b.Property<double?>("Luongcoban")
                        .HasColumnType("float")
                        .HasColumnName("LUONGCOBAN");

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<DateTime?>("Thanglam")
                        .HasColumnType("date")
                        .HasColumnName("THANGLAM");

                    b.Property<double?>("Tienkhautru")
                        .HasColumnType("float")
                        .HasColumnName("TIENKHAUTRU");

                    b.Property<double?>("Tienthuong")
                        .HasColumnType("float")
                        .HasColumnName("TIENTHUONG");

                    b.Property<double?>("Tongthunhap")
                        .HasColumnType("float")
                        .HasColumnName("TONGTHUNHAP");

                    b.HasKey("Maluong")
                        .HasName("PK__BANGLUON__D9BA4D005F975731");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("BANGLUONG");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Chatlieu", b =>
                {
                    b.Property<int>("Machatlieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACHATLIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machatlieu"));

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenchatlieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHATLIEU");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Machatlieu")
                        .HasName("PK__CHATLIEU__80F939F89D630D0C");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("CHATLIEU");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Chucvu", b =>
                {
                    b.Property<int>("Machucvu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACHUCVU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machucvu"));

                    b.Property<string>("Motachucvu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTACHUCVU");

                    b.Property<string>("Tenchucvu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCHUCVU");

                    b.HasKey("Machucvu")
                        .HasName("PK__CHUCVU__9FA9FD6AF8D6D99D");

                    b.ToTable("CHUCVU");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaoca", b =>
                {
                    b.Property<int>("Magiaoca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIAOCA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiaoca"));

                    b.Property<string>("Tenca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENCA");

                    b.Property<TimeSpan?>("Thoigianbatdau")
                        .HasColumnType("time")
                        .HasColumnName("THOIGIANBATDAU");

                    b.Property<TimeSpan?>("Thoigianketthuc")
                        .HasColumnType("time")
                        .HasColumnName("THOIGIANKETTHUC");

                    b.HasKey("Magiaoca")
                        .HasName("PK__GIAOCA__7D3545CC4C51D60B");

                    b.ToTable("GIAOCA");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaocanhanvien", b =>
                {
                    b.Property<int>("Magiaocanhanvien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIAOCANHANVIEN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiaocanhanvien"));

                    b.Property<string>("Ghichu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GHICHU");

                    b.Property<int?>("Magiaoca")
                        .HasColumnType("int")
                        .HasColumnName("MAGIAOCA");

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<DateTime?>("Ngaygiaoca")
                        .HasColumnType("date")
                        .HasColumnName("NGAYGIAOCA");

                    b.Property<string>("Sanphamdagiao")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SANPHAMDAGIAO");

                    b.Property<TimeSpan?>("Thoigianden")
                        .HasColumnType("time")
                        .HasColumnName("THOIGIANDEN");

                    b.Property<TimeSpan?>("Thoigianve")
                        .HasColumnType("time")
                        .HasColumnName("THOIGIANVE");

                    b.Property<double?>("Tiendagiao")
                        .HasColumnType("float")
                        .HasColumnName("TIENDAGIAO");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Magiaocanhanvien")
                        .HasName("PK__GIAOCANH__B0F1BCFD2684AAE1");

                    b.HasIndex("Magiaoca");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("GIAOCANHANVIEN");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giay", b =>
                {
                    b.Property<int>("Magiay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIAY");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiay"));

                    b.Property<string>("Tengiay")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENGIAY");

                    b.HasKey("Magiay")
                        .HasName("PK__GIAY__0C880C58F246FA74");

                    b.ToTable("GIAY");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaychitiet", b =>
                {
                    b.Property<int>("Magiaychitiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIAYCHITIET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiaychitiet"));

                    b.Property<double?>("Gia")
                        .HasColumnType("float")
                        .HasColumnName("GIA");

                    b.Property<int?>("Machatlieu")
                        .HasColumnType("int")
                        .HasColumnName("MACHATLIEU");

                    b.Property<int?>("Magiay")
                        .HasColumnType("int")
                        .HasColumnName("MAGIAY");

                    b.Property<int?>("Makichco")
                        .HasColumnType("int")
                        .HasColumnName("MAKICHCO");

                    b.Property<int?>("Makieudang")
                        .HasColumnType("int")
                        .HasColumnName("MAKIEUDANG");

                    b.Property<int?>("Mamausac")
                        .HasColumnType("int")
                        .HasColumnName("MAMAUSAC");

                    b.Property<int?>("Mathuonghieu")
                        .HasColumnType("int")
                        .HasColumnName("MATHUONGHIEU");

                    b.Property<string>("Mota")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MOTA");

                    b.Property<DateTime?>("Ngaysua")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSUA");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO");

                    b.Property<int?>("Nguoisua")
                        .HasColumnType("int")
                        .HasColumnName("NGUOISUA");

                    b.Property<int?>("Nguoitao")
                        .HasColumnType("int")
                        .HasColumnName("NGUOITAO");

                    b.Property<int?>("Soluongcon")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGCON");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Magiaychitiet")
                        .HasName("PK__GIAYCHIT__196AD7039127283A");

                    b.HasIndex("Machatlieu");

                    b.HasIndex("Magiay");

                    b.HasIndex("Makichco");

                    b.HasIndex("Makieudang");

                    b.HasIndex("Mamausac");

                    b.HasIndex("Mathuonghieu");

                    b.HasIndex("Nguoisua");

                    b.HasIndex("Nguoitao");

                    b.ToTable("GIAYCHITIET");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hinhthucthanhtoan", b =>
                {
                    b.Property<int>("Mahinhthucthanhtoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHINHTHUCTHANHTOAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahinhthucthanhtoan"));

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenhinhthuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENHINHTHUC");

                    b.HasKey("Mahinhthucthanhtoan")
                        .HasName("PK__HINHTHUC__C3B2561F2C27251D");

                    b.ToTable("HINHTHUCTHANHTOAN");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hoadon", b =>
                {
                    b.Property<int>("Mahoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahoadon"));

                    b.Property<string>("Diachicuahang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHICUAHANG");

                    b.Property<string>("Emailcuahang")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAILCUAHANG");

                    b.Property<string>("Ghichu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("GHICHU");

                    b.Property<int?>("Mahinhthucthanhtoan")
                        .HasColumnType("int")
                        .HasColumnName("MAHINHTHUCTHANHTOAN");

                    b.Property<int?>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<int?>("Mauudai")
                        .HasColumnType("int")
                        .HasColumnName("MAUUDAI");

                    b.Property<DateTime?>("Ngaytao")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO");

                    b.Property<string>("Sdtcuahang")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDTCUAHANG");

                    b.Property<string>("Tencuahang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TENCUAHANG");

                    b.Property<double?>("Tongtien")
                        .HasColumnType("float")
                        .HasColumnName("TONGTIEN");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mahoadon")
                        .HasName("PK__HOADON__A4999DF5068B15D4");

                    b.HasIndex("Mahinhthucthanhtoan");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Mataikhoan");

                    b.HasIndex("Mauudai");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hoadonchitiet", b =>
                {
                    b.Property<int>("Mahoadonchitiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHOADONCHITIET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahoadonchitiet"));

                    b.Property<double?>("Gia")
                        .HasColumnType("float")
                        .HasColumnName("GIA");

                    b.Property<int?>("Magiaychitiet")
                        .HasColumnType("int")
                        .HasColumnName("MAGIAYCHITIET");

                    b.Property<int?>("Mahoadon")
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    b.Property<int?>("Soluongmua")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONGMUA");

                    b.HasKey("Mahoadonchitiet")
                        .HasName("PK__HOADONCH__EF957FF0F67F56CB");

                    b.HasIndex("Magiaychitiet");

                    b.HasIndex("Mahoadon");

                    b.ToTable("HOADONCHITIET");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Khachhang", b =>
                {
                    b.Property<int>("Makhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makhachhang"));

                    b.Property<int?>("Diemkhachhang")
                        .HasColumnType("int")
                        .HasColumnName("DIEMKHACHHANG");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenkhachhang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKHACHHANG");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Makhachhang")
                        .HasName("PK__KHACHHAN__30035C2F2F2CC38D");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Kichco", b =>
                {
                    b.Property<int>("Makichco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKICHCO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makichco"));

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenkichco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKICHCO");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Makichco")
                        .HasName("PK__KICHCO__7EDFFF29EF6EA5B0");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("KICHCO");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Kieudang", b =>
                {
                    b.Property<int>("Makieudang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKIEUDANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makieudang"));

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenkieudang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENKIEUDANG");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Makieudang")
                        .HasName("PK__KIEUDANG__877F27F20BB7C69B");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("KIEUDANG");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Mausac", b =>
                {
                    b.Property<int>("Mamausac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAMAUSAC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mamausac"));

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tenmausac")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENMAUSAC");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mamausac")
                        .HasName("PK__MAUSAC__99E7A68FD4EBC4CB");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("MAUSAC");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Taikhoan", b =>
                {
                    b.Property<int>("Mataikhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mataikhoan"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("Gioitinh")
                        .HasColumnType("bit")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hovaten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOVATEN");

                    b.Property<int>("Machucvu")
                        .HasColumnType("int")
                        .HasColumnName("MACHUCVU");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<DateTime?>("Ngaytaotaikhoan")
                        .HasColumnType("date")
                        .HasColumnName("NGAYTAOTAIKHOAN");

                    b.Property<string>("Pasword")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("PASWORD");

                    b.Property<string>("Sodienthoai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SODIENTHOAI");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Mataikhoan")
                        .HasName("PK__TAIKHOAN__2ED8B51783411548");

                    b.HasIndex("Machucvu");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Thuonghieu", b =>
                {
                    b.Property<int>("Mathuonghieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATHUONGHIEU");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mathuonghieu"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("EMAIL");

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tenthuonghieu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENTHUONGHIEU");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mathuonghieu")
                        .HasName("PK__THUONGHI__B319F638CB3C0B76");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("THUONGHIEU");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Uudai", b =>
                {
                    b.Property<int>("Mauudai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAUUDAI");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mauudai"));

                    b.Property<int?>("Mataikhoan")
                        .HasColumnType("int")
                        .HasColumnName("MATAIKHOAN");

                    b.Property<DateTime?>("Ngaybatdau")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYBATDAU");

                    b.Property<DateTime?>("Ngayketthuc")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYKETTHUC");

                    b.Property<int?>("Phantram")
                        .HasColumnType("int")
                        .HasColumnName("PHANTRAM");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tenuudai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENUUDAI");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mauudai")
                        .HasName("PK__UUDAI__3F58B4FD7443E6FD");

                    b.HasIndex("Mataikhoan");

                    b.ToTable("UUDAI");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Bangluong", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Bangluongs")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__BANGLUONG__MATAI__5629CD9C");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Chatlieu", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Chatlieus")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__CHATLIEU__MATAIK__571DF1D5");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaocanhanvien", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Giaoca", "MagiaocaNavigation")
                        .WithMany("Giaocanhanviens")
                        .HasForeignKey("Magiaoca")
                        .HasConstraintName("FK__GIAOCANHA__MAGIA__5812160E");

                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Giaocanhanviens")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__GIAOCANHA__MATAI__59063A47");

                    b.Navigation("MagiaocaNavigation");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaychitiet", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Chatlieu", "MachatlieuNavigation")
                        .WithMany("Giaychitiets")
                        .HasForeignKey("Machatlieu")
                        .HasConstraintName("FK__GIAYCHITI__MACHA__59FA5E80");

                    b.HasOne("DAL.Models.DomainClass.Giay", "MagiayNavigation")
                        .WithMany("Giaychitiets")
                        .HasForeignKey("Magiay")
                        .HasConstraintName("FK__GIAYCHITI__MAGIA__5AEE82B9");

                    b.HasOne("DAL.Models.DomainClass.Kichco", "MakichcoNavigation")
                        .WithMany("Giaychitiets")
                        .HasForeignKey("Makichco")
                        .HasConstraintName("FK__GIAYCHITI__MAKIC__5BE2A6F2");

                    b.HasOne("DAL.Models.DomainClass.Kieudang", "MakieudangNavigation")
                        .WithMany("Giaychitiets")
                        .HasForeignKey("Makieudang")
                        .HasConstraintName("FK__GIAYCHITI__MAKIE__5CD6CB2B");

                    b.HasOne("DAL.Models.DomainClass.Mausac", "MamausacNavigation")
                        .WithMany("Giaychitiets")
                        .HasForeignKey("Mamausac")
                        .HasConstraintName("FK__GIAYCHITI__MAMAU__5DCAEF64");

                    b.HasOne("DAL.Models.DomainClass.Thuonghieu", "MathuonghieuNavigation")
                        .WithMany("Giaychitiets")
                        .HasForeignKey("Mathuonghieu")
                        .HasConstraintName("FK__GIAYCHITI__MATHU__5EBF139D");

                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "NguoisuaNavigation")
                        .WithMany("GiaychitietNguoisuaNavigations")
                        .HasForeignKey("Nguoisua")
                        .HasConstraintName("FK__GIAYCHITI__NGUOI__60A75C0F");

                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "NguoitaoNavigation")
                        .WithMany("GiaychitietNguoitaoNavigations")
                        .HasForeignKey("Nguoitao")
                        .HasConstraintName("FK__GIAYCHITI__NGUOI__5FB337D6");

                    b.Navigation("MachatlieuNavigation");

                    b.Navigation("MagiayNavigation");

                    b.Navigation("MakichcoNavigation");

                    b.Navigation("MakieudangNavigation");

                    b.Navigation("MamausacNavigation");

                    b.Navigation("MathuonghieuNavigation");

                    b.Navigation("NguoisuaNavigation");

                    b.Navigation("NguoitaoNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hoadon", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Hinhthucthanhtoan", "MahinhthucthanhtoanNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Mahinhthucthanhtoan")
                        .HasConstraintName("FK__HOADON__MAHINHTH__619B8048");

                    b.HasOne("DAL.Models.DomainClass.Khachhang", "MakhachhangNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Makhachhang")
                        .HasConstraintName("FK__HOADON__MAKHACHH__628FA481");

                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__HOADON__MATAIKHO__6383C8BA");

                    b.HasOne("DAL.Models.DomainClass.Uudai", "MauudaiNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("Mauudai")
                        .HasConstraintName("FK__HOADON__MAUUDAI__6477ECF3");

                    b.Navigation("MahinhthucthanhtoanNavigation");

                    b.Navigation("MakhachhangNavigation");

                    b.Navigation("MataikhoanNavigation");

                    b.Navigation("MauudaiNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hoadonchitiet", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Giaychitiet", "MagiaychitietNavigation")
                        .WithMany("Hoadonchitiets")
                        .HasForeignKey("Magiaychitiet")
                        .HasConstraintName("FK__HOADONCHI__MAGIA__656C112C");

                    b.HasOne("DAL.Models.DomainClass.Hoadon", "MahoadonNavigation")
                        .WithMany("Hoadonchitiets")
                        .HasForeignKey("Mahoadon")
                        .HasConstraintName("FK__HOADONCHI__MAHOA__66603565");

                    b.Navigation("MagiaychitietNavigation");

                    b.Navigation("MahoadonNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Kichco", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Kichcos")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__KICHCO__MATAIKHO__6754599E");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Kieudang", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Kieudangs")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__KIEUDANG__MATAIK__68487DD7");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Mausac", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Mausacs")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__MAUSAC__MATAIKHO__693CA210");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Taikhoan", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Chucvu", "MachucvuNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("Machucvu")
                        .IsRequired()
                        .HasConstraintName("FK__TAIKHOAN__MACHUC__6A30C649");

                    b.Navigation("MachucvuNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Thuonghieu", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Thuonghieus")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__THUONGHIE__MATAI__6B24EA82");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Uudai", b =>
                {
                    b.HasOne("DAL.Models.DomainClass.Taikhoan", "MataikhoanNavigation")
                        .WithMany("Uudais")
                        .HasForeignKey("Mataikhoan")
                        .HasConstraintName("FK__UUDAI__MATAIKHOA__6C190EBB");

                    b.Navigation("MataikhoanNavigation");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Chatlieu", b =>
                {
                    b.Navigation("Giaychitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Chucvu", b =>
                {
                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaoca", b =>
                {
                    b.Navigation("Giaocanhanviens");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giay", b =>
                {
                    b.Navigation("Giaychitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Giaychitiet", b =>
                {
                    b.Navigation("Hoadonchitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hinhthucthanhtoan", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Hoadon", b =>
                {
                    b.Navigation("Hoadonchitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Kichco", b =>
                {
                    b.Navigation("Giaychitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Kieudang", b =>
                {
                    b.Navigation("Giaychitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Mausac", b =>
                {
                    b.Navigation("Giaychitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Taikhoan", b =>
                {
                    b.Navigation("Bangluongs");

                    b.Navigation("Chatlieus");

                    b.Navigation("Giaocanhanviens");

                    b.Navigation("GiaychitietNguoisuaNavigations");

                    b.Navigation("GiaychitietNguoitaoNavigations");

                    b.Navigation("Hoadons");

                    b.Navigation("Kichcos");

                    b.Navigation("Kieudangs");

                    b.Navigation("Mausacs");

                    b.Navigation("Thuonghieus");

                    b.Navigation("Uudais");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Thuonghieu", b =>
                {
                    b.Navigation("Giaychitiets");
                });

            modelBuilder.Entity("DAL.Models.DomainClass.Uudai", b =>
                {
                    b.Navigation("Hoadons");
                });
#pragma warning restore 612, 618
        }
    }
}
